/// Flutter icons Tk
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tk
///      fonts:
///       - asset: fonts/Tk.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Tk {
  Tk._();

  static const _kFontFam = 'Tk';
  static const String? _kFontPkg = null;

  static const IconData age = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawmenu = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uni_1 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
